import { Map, Marker } from 'pigeon-maps'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Header from './compo/Header';

export default function Contact() {
    return (<>
        <Head>
        <title>Store | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
        <div className={styles.container}>
            <div className={styles.maps}>
                <Map  defaultCenter={[34.9206089, -1.3259371]} defaultZoom={15} boxClassname={styles.maps} warningZIndex={-1}>
                    <Marker 
                        width={20}
                        anchor={[34.9206089, -1.3259371]} 
                        color={"#ccc"} 
                    />
                </Map>
            </div>
            <div className={styles.contact}>
                <h1>Contact</h1>
                <label className={styles.label}>City</label><br/>
                <label className={styles.info}>Tlmecen</label><br/>
                <label className={styles.label}>Addres</label><br/>
                <label className={styles.info}>144 logs Oudjlida Tlemcen</label><br/>
                <label className={styles.label}>Phone</label><br/>
                <label className={styles.info}>+213 542147570</label><br/>
                <label className={styles.label}>Email</label><br/>
                <label className={styles.info}>abdennour.mez160@gmail.com</label><br/>
            </div>
        </div>
        </>
    )
}//34.9206089,-1.3259371,18z