import Header from './compo/Header';
import styles from '../styles/Home.module.css'
import Head from "next/head"

export default function Store () {
    let rows = []
    for (let i = 0; i < 16; i++) {
        rows.push(<div className={styles.store__box}>
            <div className={styles.store__image}></div>
            <div className={styles.store__title}>Discord Nitro</div>
            <div className={styles.store__description}>Lorem ipsum dolor sit amet</div>
            <button className={styles.store__btn}>Add to cart</button>
        </div>)
        
    }
    return(
        <>
        <Head>
            <title>Store | SHOP</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
        <div className={styles.container}>
            
            <div className={styles.store__header}><h1>Shop</h1></div>
            <div className={styles.store__grid}>
                {rows}
            </div>
        </div>
        <footer className={styles.footer}>
                <h3>Created by: <a href="https://abdennour.me">Abdennour Mez</a></h3>
            </footer>
        </>
    )
}